### ISSUE TITLE
[Crash]: Crash when any resource packs are loaded

### ISSUE THREAD

**Issue by katubug** [Fuzss/resourcepackoverrides#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.2

### Notes (Required)

1. Configure default resourcepacks
2. Launch game

In all honesty, I am not sure that this crash is due to this mod. However, I hoped that you might have some insight on what the issue could be. Thanks for your time!

### Crash Report (Required)

https://gist.github.com/katubug/04d946d2879dbb9d6abaf1cb923ebca0

**Comment by Fuzss** [comment]
Looks like Minecraft::player is being accessed while it is still null which is the case when no world is loaded.
The crash unfortunately contains no hint at the exact cause, especially since I'm unable to deobfuscate it.
The Zip file error might be be caused as a result of the crash, doesn't look like something to worry about.
